### ISSUE TITLE
report/results/TCGA_RNASeq_PanCancer.RData not found

### ISSUE THREAD

**Issue by xin-yang123** [XSLiuLab/tumor-immunogenicity-score#6]
Hello, I did not find TCGA_RNASeq_PanCancer.RData data file in this folder

**Comment by ShixiangWang** [comment]
@xin-yang123 Yeah, it is too large to keep in GitHub. You  can download it from https://figshare.com/articles/TCGA_RNASeq_PanCancer_RData/12317648
