### ISSUE TITLE
Can I apply this method to just only one sample analysis?

### ISSUE THREAD

**Issue by pl618** [XSLiuLab/tumor-immunogenicity-score#7]
Hi, I want to apply this method to analysis new sample RNA-seq data. It seems that it does not work for one sample, but when I change GSVA method to ''ssgsea", it runs.

I want to know if "ssgsea" for one sample's output meaningful?

Thanks!

```

> applyGSVA(merged_geneList_common, group_col = "Cell_type", gene_col = "Symbol", ExprMatList =list(tpm_mat_common), method = "gsva") -> res_GSVA
Error in .local(expr, gset.idx.list, ...) : 
  Less than two genes in the input expression data matrix
In addition: Warning messages:
1: In .local(expr, gset.idx.list, ...) :
  516 genes with constant expression values throuhgout the samples.
2: In .local(expr, gset.idx.list, ...) :
 
 Error in .local(expr, gset.idx.list, ...) : 
  Less than two genes in the input expression data matrix 
> applyGSVA(merged_geneList_common, group_col = "Cell_type", gene_col = "Symbol", ExprMatList =list(tpm_mat_common), method = "ssgsea") -> res_GSVA
Estimating ssGSEA scores for 26 gene sets.
  |                                                                                                                                                                                    |   0%Using parallel with 4 cores
  |====================================================================================================================================================================================| 100%
Warning message:
In .local(expr, gset.idx.list, ...) :
  516 genes with constant expression values throuhgout the samples.
> res_GSVA
[[1]]
           aDC Angiogenesis       APM     B cells CD8 T cells Cytotoxic cells          DC Eosinophils        iDC Macrophages Mast cells Neutrophils NK CD56bright cells NK CD56dim cells
TPM -0.1124977 -0.001057342 0.5979771 -0.04583635   0.2513935     -0.02563596 -0.03601384  0.07173081 0.04598423   0.1912207 -0.2183319  0.03906639          0.01845954      -0.06450661
     NK cells        pDC     T cells T helper cells Tcm cells Tem cells   Tfh cells  Tgd cells  Th1 cells Th17 cells    Th2 cells Treg cells
TPM 0.0761799 -0.3843792 -0.00658121      0.2967451 0.1318536 0.1282695 -0.05952038 -0.1437911 -0.0240773  0.0296016 -0.006756854 -0.4020229
```

**Comment by ShixiangWang** [comment]
@plsysu Yeah, you can use the result and it has similar biological meaning. But note that the value is not comparable to GSVA values from other methods.

**Comment by pl618** [comment]
Thanks for your reply. I got it. But I have another question: Since the paper proved that TIGS score is better than TMB to predict ICI drug response, how to calculate TIGS score to a new sample except TCGA training data?

**Comment by ShixiangWang** [comment]
Nope. The project provides an advanced concept that APM enrichment score and log(TMB) can be linearly combined. We explored and validated the combined value with TCGA and ICI datasets. However, we did not provide a ready-to-go program to predict single sample ICI response. This needs further work. As you can see in manuscript method, the APM score are necessarily scaled to 0-1 region based on TCGA pan cancer dataset. We need a TCGA independent method to construct a score for single sample ICI response prediction.

Are you using TIGS for clinical sample? Currently, it is not recommended. Many works are optimizing TMB and I think APS and its combination with TMB also should be optimized. And many factors also affect the response.

Currently, I have no plan to build a model for single sample prediction. So I am sorry to tell your that TIGS only works when you have multiple samples. 

@plsysu Thanks for your question. I think it is valuable to do some further modeling work for single sample prediction. I will let a member of my lab to follow this and see how it goes.

**Comment by pl618** [comment]
Thanks for your detailed discussion and concerns for works on my question. I investigate and survey biomarkers related to ICI response, and have a purpose for clinical use. As you recommended, I will carefully think about TIGS for clinical use.

**Comment by ShixiangWang** [comment]
Yeah, for clinical use, we have to optimize what we got and set a reasonable cutoff for classify samples.

**Comment by svaranas123** [comment]
Hi, I am trying to run the applyGVSA but it says duplicate row.names are not allowed. please help resolve. applyGSVA(merged_geneList, group_col = "Cell_type", gene_col = "Symbol", ExprMatList = list(RNASeq_pancan), method = "gsva") -> res_pancan.GSVA
Error in `.rowNamesDF<-`(x, value = value) : 
  duplicate 'row.names' are not allowed
In addition: Warning message:
non-unique values when setting 'row.names': ‘?|100130426’, ‘?|100133144’, ‘?|100134869’, ‘?|10357’, ‘?|10431’, ‘?|136542’, ‘?|155060’, ‘?|26823’, ‘?|280660’, ‘?|317712’, ‘?|340602’, ‘?|388795’, ‘?|390284’, ‘?|391343’, ‘?|391714’, ‘?|404770’, ‘?|441362’, ‘?|442388’, ‘?|553137’, ‘?|57714’, ‘?|645851’, ‘?|652919’, ‘?|653553’, ‘?|728045’, ‘?|728603’, ‘?|728788’, ‘?|729884’, ‘?|8225’, ‘?|90288’, ‘A1BG’, ‘A1CF’, ‘A2BP1’, ‘A2LD1’, ‘A2M’, ‘A2ML1’, ‘A4GALT’, ‘A4GNT’, ‘AAA1’, ‘AAAS’, ‘AACS’, ‘AACSL’, ‘AADAC’, ‘AADACL2’, ‘AADACL3’, ‘AADACL4’, ‘AADAT’, ‘AAGAB’, ‘AAK1’, ‘AAMP’, ‘AANAT’, ‘AARS’, ‘AARS2’, ‘AARSD1’, ‘AASDH’, ‘AASDHPPT’, ‘AASS’, ‘AATF’, ‘AATK’, ‘ABAT’, ‘ABCA1’, ‘ABCA10’, ‘ABCA11P’, ‘ABCA12’, ‘ABCA13’, ‘ABCA17P’, ‘ABCA2’, ‘AB [... truncated] 
Called from: `.rowNamesDF<-`(x, value = value)
Browse[1]>
